# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: python-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: v1
kind: Service
metadata:
  name: python-hello-world
spec:
  type: LoadBalancer
  selector:
    app: python-hello-world
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world
  labels:
    name: python-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-hello-world
      tier: frontend
  template:
    metadata:
      labels:
        app: python-hello-world
        tier: frontend
    spec:
      containers:
      - name: server
        image: python-hello-world
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MYSQL_DB_HOST
          value: flask-mysql
#        - name: INSTANCE_HOST
#          value: "172.17.0.3"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "Hangzhou123"
        - name: DB_NAME
          value: "mydb"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5